<h1>Delete Access Privilege</h1>

<p>Are you sure that you want to delete this access privilege?</p>
<dl class="dl-horizontal">
    <dt>Privilege</dt><dd><?php echo $this->escapeHtml($this->privilege->getPrivilege()); ?></dd>
    <dt>Display Name</dt><dd><?php echo $this->escapeHtml($this->privilege->getDisplayName()); ?></dd>
</dl>
 <?php
 $url = $this->url('civaccess/default', array(
     'controller' => 'privilege',
     'action'     => 'delete',
     'id'         => $this->privilege->getPrivilegeId(),
 ));
 ?>
<form action="<?php echo $url; ?>" method="post">
    <div>
        <input type="hidden" name="id" value="<?php echo (int) $this->privilege->getPrivilegeId(); ?>" />
        <input class="btn btn-sm btn-primary" type="submit" name="del" value="Yes" />
        <input class="btn btn-sm btn-default" type="submit" name="del" value="No" />
    </div>
</form>
