<h1>Delete Access Role</h1>

<p>Are you sure that you want to delete this role?</p>
<dl class="dl-horizontal">
    <dt>Role</dt><dd><?php echo $this->escapeHtml($this->role->getRole()); ?></dd>
    <dt>Inherits from</dt><dd><?php echo $this->escapeHtml($this->role->getParent()); ?></dd>
    <dt>Role Type</dt><dd><?php echo $this->escapeHtml($this->role->getRoleType()); ?></dd>
</dl>
 <?php
 $url = $this->url('civaccess/default', array(
     'controller' => 'role',
     'action'     => 'delete',
     'id'         => $this->role->getRoleId(),
 ));
 ?>
<form action="<?php echo $url; ?>" method="post">
    <div>
        <input type="hidden" name="id" value="<?php echo (int) $this->role->getRoleId(); ?>" />
        <input class="btn btn-primary" type="submit" name="del" value="Yes" />
        <input class="btn btn-default" type="submit" name="del" value="No" />
    </div>
</form>
