<div class="row">
    <div class="col-lg-12">
        <h1>Edit role</h1>
        
        <?php
            $form = $this->form;
            $form->setAttribute('action', $this->url('civaccess/default', array('controller' => 'role', 'action' => 'edit', 'id' => $this->roleId)))
                 ->prepare();
            echo $this->form()->openTag($form);
        ?>
        
        <div class="form-group">
            <?php echo $this->formRow($form->get('role')); ?>
        </div>
        
        <div class="form-group">
            <?php echo $this->formRow($form->get('parent')); ?>
        </div>
        
        <?php echo $this->formSubmit($form->get('submit')); ?>
        <?php echo $this->form()->closeTag(); ?>
        
    </div>
</div>