<script>
    $( document ).ready(function() {
        $( "select[name='resource']" ).prepend( '<option hidden selected></option>' );
        $( "select[name='resource']" ).change(function() {
            
            var resourceId = $( "select[name='resource']" ).val();

            $.ajax({
                url: '/access/privilege/json/' + resourceId,
                headers: {          
                    Accept : "application/json; charset=utf-8",   
                },      
                success : function(response) {
                    var selectElement = $("select[name='privilege']");
                    selectElement.find('option').remove();
                    var arrayLength = response.length;
                    for (var i = 0; i < arrayLength; i++) {
                        console.log(response[i].privilegeId);
                        selectElement.append($("<option></option>")
                            .attr("value",response[i].privilegeId)
                            .text(response[i].displayName)); 
                    }
                }
            });
   
        });
    });
</script>

<div class="row">
    <div class="col-lg-12">
        <h1>Add new access rule</h1>
        
        <?php
            $form = $this->form;
            $form->setAttribute('action', $this->url('civaccess/default', array('controller' => 'rule', 'action' => 'add')))
                 ->prepare();
            echo $this->form()->openTag($form);
        ?>
        
        <div class="form-group">
            <?php echo $this->formRow($form->get('role')); ?>
        </div>
        
        <div class="form-group">
            <?php echo $this->formRow($form->get('resource')); ?>
        </div>
        
        <div class="form-group">
            <?php echo $this->formRow($form->get('privilege')); ?>
        </div>
        
        <?php echo $this->formSubmit($form->get('submit')); ?>
        <?php echo $this->form()->closeTag(); ?>
        
    </div>
</div>