<div class="row">
    <div class="col-lg-12">
        <h1>Add new access rule</h1>
        
        <?php
            $form = $this->form;
            $form->setAttribute('action', $this->url('civaccess/default', array('controller' => 'rule', 'action' => 'add')))
                 ->prepare();
            echo $this->form()->openTag($form);
        ?>
        
        <div class="form-group">
            <?php echo $this->formRow($form->get('role')); ?>
        </div>
        
        <div class="form-group">
            <?php echo $this->formRow($form->get('resource')); ?>
        </div>
        
        <div class="form-group">
            <?php echo $this->formRow($form->get('privilege')); ?>
        </div>
        
        <?php echo $this->formSubmit($form->get('submit')); ?>
        <?php echo $this->form()->closeTag(); ?>
        
    </div>
</div>