<h1>Delete Access Rule</h1>

<p>Are you sure that you want to delete this access rule?</p>
<dl class="dl-horizontal">
    <dt>Role</dt><dd><?php echo $this->escapeHtml($this->rule->getRole()); ?></dd>
    <dt>Resource</dt><dd><?php echo $this->escapeHtml($this->rule->getResource()); ?></dd>
    <dt>Privilege</dt><dd><?php echo $this->escapeHtml($this->rule->getPrivilege()); ?></dd>
</dl>
 <?php
 $url = $this->url('civaccess/default', array(
     'controller' => 'rule',
     'action'     => 'delete',
     'id'         => $this->rule->getRuleId(),
 ));
 ?>
<form action="<?php echo $url; ?>" method="post">
    <div>
        <input type="hidden" name="id" value="<?php echo (int) $this->rule->getRuleId(); ?>" />
        <input class="btn btn-sm btn-primary" type="submit" name="del" value="Yes" />
        <input class="btn btn-sm btn-default" type="submit" name="del" value="No" />
    </div>
</form>
